/*Query 06*/
SELECT LOC
FROM EMP
         INNER JOIN DEPT D on D.DEPTNO = EMP.DEPTNO
    AND ENAME = 'ALLEN';

/*Query 07*/
SELECT *
FROM EMP EMPLOYEE
         INNER JOIN EMP E ON E.EMPNO = EMPLOYEE.MGR
    AND EMPLOYEE.SAL > E.SAL;

/*Query 08*/
SELECT COUNT(*), EXTRACT(YEAR FROM TO_DATE(HIREDATE, 'DD-MM-YYYY'))
FROM EMP
GROUP BY EXTRACT(YEAR FROM TO_DATE(HIREDATE, 'DD-MM-YYYY'))
ORDER BY EXTRACT(YEAR FROM TO_DATE(HIREDATE, 'DD-MM-YYYY'));

/*Query 09*/
SELECT *
FROM EMP
WHERE JOB IN
      (SELECT DISTINCT JOB
       FROM EMP
                INNER JOIN (SELECT DEPTNO FROM DEPT WHERE LOC = 'CHICAGO') D ON D.DEPTNO = EMP.DEPTNO)