/*Query 01*/
SELECT PLAYERS.PLAYERNO, NAME, INITIALS, COUNT(WON)
FROM PLAYERS
         INNER JOIN MATCHES M ON PLAYERS.PLAYERNO = M.PLAYERNO
GROUP BY PLAYERS.PLAYERNO, NAME, INITIALS
ORDER BY COUNT(WON) DESC;

/*Query 02*/
SELECT NAME, PEN_DATE, AMOUNT
FROM PENALTIES
         INNER JOIN PLAYERS P ON PENALTIES.PLAYERNO = P.PLAYERNO
ORDER BY AMOUNT DESC;

/*Query 03*/
SELECT TEAMNO, NAME
FROM TEAMS
        INNER JOIN PLAYERS P ON TEAMS.PLAYERNO = P.PLAYERNO;

/*Query 04*/
SELECT NAME, WON, LOST
FROM PLAYERS
         INNER JOIN MATCHES M on PLAYERS.PLAYERNO = M.PLAYERNO
    AND WON > LOST;

/*Query 05*/
SELECT PLAYERS.PLAYERNO, PLAYERS.NAME, SUM(AMOUNT)
FROM PLAYERS
         INNER JOIN PENALTIES P on PLAYERS.PLAYERNO = P.PLAYERNO
GROUP BY PLAYERS.PLAYERNO, PLAYERS.NAME
ORDER BY SUM(AMOUNT) ASC;