/*Query 05*/
SELECT *
FROM EMP EMPLOYEE
WHERE SAL >
      (SELECT AVG(SAL)
       FROM EMP EMPLOYEEAVG
       WHERE EMPLOYEEAVG.DEPTNO = EMPLOYEE.DEPTNO);

/*Query 06*/
SELECT *
FROM DEPT
WHERE DEPTNO IN
      (SELECT DISTINCT DEPTNO
       FROM EMP);

/*Query 07*/
SELECT *
FROM DEPT
WHERE DEPTNO IN
      (SELECT DISTINCT DEPTNO
       FROM EMP
       WHERE SAL > 1000);

/*Query 08*/
SELECT *
FROM DEPT
WHERE DEPTNO IN
      (SELECT DEPTNO
       FROM EMP
      GROUP BY DEPTNO
       HAVING MIN(SAL) > 1000);