/*Query 01*/
SELECT NAME
FROM PLAYERS
WHERE PLAYERNO =
      (SELECT PLAYERNO
       FROM MATCHES
       GROUP BY PLAYERNO
       HAVING COUNT(DISTINCT TEAMNO) > 1);

/*Query 02*/
SELECT NAME, INITIALS
FROM PLAYERS
WHERE PLAYERNO NOT IN
      (SELECT PLAYERNO
       FROM PENALTIES
       WHERE EXTRACT(YEAR FROM PEN_DATE) = 1980);

/*Query 03*/
SELECT PLAYERNO, NAME
FROM PLAYERS
WHERE PLAYERNO IN
      (SELECT PLAYERNO
       FROM PENALTIES
       WHERE AMOUNT > 80);

/*Query 04*/
SELECT PLAYERNO, NAME
FROM PLAYERS
WHERE PLAYERNO IN
      (SELECT PLAYERNO
       FROM PENALTIES
       GROUP BY PLAYERNO
       HAVING MIN(AMOUNT) > 80);