/*Queries 05*/
SELECT EMP.EMPNO, EMP.ENAME, EMP.JOB, LPAD(MGR, lvl * 5, '') AS MGR, LVL
FROM EMP,
     (SELECT empno, LEVEL AS lvl
      FROM emp
      CONNECT BY PRIOR EMPNO = MGR
      START WITH MGR = (SELECT EMPNO FROM EMP WHERE ENAME = 'JONES')) P
WHERE P.EMPNO = EMP.EMPNO
ORDER BY MGR DESC;

/*Queries 06*/
SELECT EMP.EMPNO, ENAME, JOB, MGR, LVL
FROM EMP,
     (SELECT LEVEL AS LVL, EMPNO
      FROM EMP
      CONNECT BY PRIOR MGR = EMPNO
      START WITH EMPNO =
                 (SELECT EMPNO
                  FROM EMP
                  WHERE ENAME = 'SMITH')) P
WHERE P.EMPNO = EMP.EMPNO;

/*Queries 07*/
SELECT LVL, ROUND(AVG(SAL), 2)
FROM EMP,
     (SELECT LEVEL AS LVL, EMPNO
         FROM EMP
         CONNECT BY PRIOR EMPNO = MGR
         START WITH EMPNO = (SELECT EMPNO FROM EMP WHERE ENAME = 'KING')) P
WHERE P.EMPNO = EMP.EMPNO
GROUP BY LVL;
