/*Queries 02*/
SELECT PARTS.SUPER, PARTS.SUB
FROM PARTS,
     (SELECT DISTINCT SUPER
         FROM parts
         CONNECT BY PRIOR SUB = SUPER
         START WITH SUPER in ('P3', 'P9')) P
WHERE PARTS.SUPER = P.SUPER;

/*Queries 03*/
SELECT LVL, PARTS.SUPER, PARTS.SUB
FROM PARTS,
     (SELECT LEVEL AS LVL, SUB
      FROM PARTS
      CONNECT BY PRIOR SUB = SUPER
      START WITH SUPER = ('P1')) P
WHERE P.SUB = PARTS.SUB
  AND P.SUB = 'P12';

/*Queries 04*/
SELECT PARTS.SUB, PARTS.PRICE
FROM PARTS,
     (SELECT SUB, PRICE
      FROM PARTS
      CONNECT BY PRIOR SUB = SUPER
      START WITH SUPER = ('P1')) P
WHERE P.PRICE > 20
  AND PARTS.SUB = P.SUB;