/*Query 01*/
SELECT TEAMNO
FROM TEAMS
WHERE PLAYERNO = 27
  AND TEAMNO != 1;

/*Query 02*/
SELECT PLAYERS.PLAYERNO, NAME, INITIALS
FROM PLAYERS,
     MATCHES
WHERE MATCHES.PLAYERNO = PLAYERS.PLAYERNO
  AND MATCHES.WON > 0
GROUP BY PLAYERS.PLAYERNO, NAME, INITIALS;

/*Query 03*/
SELECT PLAYERS.PLAYERNO, NAME
FROM PLAYERS,
     PENALTIES
WHERE PENALTIES.PLAYERNO = PLAYERS.PLAYERNO
GROUP BY PLAYERS.PLAYERNO, NAME;

/*Query 04*/
SELECT PLAYERS.PLAYERNO, NAME
FROM PLAYERS,
     PENALTIES
WHERE PENALTIES.PLAYERNO = PLAYERS.PLAYERNO
  AND AMOUNT > 50
GROUP BY PLAYERS.PLAYERNO, NAME;

/*Query 05*/
SELECT PLAYERNO, NAME
FROM PLAYERS
WHERE YEAR_OF_BIRTH =
      (SELECT YEAR_OF_BIRTH
       FROM PLAYERS
       WHERE INITIALS = 'R'
         AND NAME = 'Parmenter');

/*Query 06*/
SELECT PLAYERNO, NAME
FROM PLAYERS
WHERE YEAR_OF_BIRTH =
      (SELECT MAX(YEAR_OF_BIRTH)
       FROM PLAYERS);