/*Query 05*/
SELECT *
FROM EMP EMPLOYEE
WHERE SAL >
      (SELECT AVG(SAL)
       FROM EMP EMPLOYEEAVG
       WHERE EMPLOYEEAVG.DEPTNO = EMPLOYEE.DEPTNO);

/*Query 06*/
SELECT DISTINCT DEPT.DEPTNO, DNAME, LOC
FROM DEPT
         INNER JOIN EMP ON DEPT.DEPTNO = EMP.DEPTNO
ORDER BY DEPTNO;

/*Query 07*/
SELECT DEPT.DEPTNO
FROM DEPT
         INNER JOIN
     (SELECT DEPTNO, MAX(SAL) MAX
      FROM EMP
      GROUP BY DEPTNO) D
     ON D.DEPTNO = DEPT.DEPTNO
         AND MAX > 1000;

/*Query 08*/
SELECT DEPT.DEPTNO
FROM DEPT
         INNER JOIN
     (SELECT DEPTNO, MIN(SAL) MIN
      FROM EMP
      GROUP BY DEPTNO) D
     ON D.DEPTNO = DEPT.DEPTNO
         AND MIN > 1000;