/*Query 01*/
SELECT NAME
FROM PLAYERS
         JOIN MATCHES M ON PLAYERS.PLAYERNO = M.PLAYERNO
GROUP BY NAME
HAVING COUNT(DISTINCT TEAMNO) > 1;

/*Query 02*/
SELECT NAME, INITIALS
FROM PLAYERS
         LEFT JOIN
     (SELECT PLAYERNO
      FROM PENALTIES
      WHERE EXTRACT(YEAR FROM PEN_DATE) = 1980) P ON PLAYERS.PLAYERNO = P.PLAYERNO
WHERE P.PLAYERNO IS NULL;

/*Query 03*/
SELECT DISTINCT PLAYERS.PLAYERNO, NAME
FROM PLAYERS
         INNER JOIN PENALTIES P ON PLAYERS.PLAYERNO = P.PLAYERNO
    AND P.AMOUNT > 80;

/*Query 04*/
SELECT PLAYERS.PLAYERNO, NAME
FROM PLAYERS
         INNER JOIN (SELECT PENALTIES.PLAYERNO, MIN(AMOUNT) AS P
                     FROM PENALTIES
                     GROUP BY PENALTIES.PLAYERNO
                     HAVING MIN(AMOUNT) > 80) Q
                    ON PLAYERS.PLAYERNO = Q.PLAYERNO;