/*Query 01*/
SELECT PLAYERS.PLAYERNO, NAME, INITIALS, COUNT(WON)
FROM PLAYERS,
     MATCHES
WHERE PLAYERS.PLAYERNO = MATCHES.PLAYERNO
GROUP BY PLAYERS.PLAYERNO, NAME, INITIALS
ORDER BY COUNT(WON) DESC;

/*Query 02*/
SELECT NAME, PEN_DATE, AMOUNT
FROM PENALTIES,
     PLAYERS
WHERE PLAYERS.PLAYERNO = PENALTIES.PLAYERNO
ORDER BY AMOUNT DESC;

/*Query 03*/
SELECT TEAMNO, NAME
FROM TEAMS,
     PLAYERS
WHERE TEAMS.PLAYERNO = PLAYERS.PLAYERNO;

/*Query 04*/
SELECT NAME, WON, LOST
FROM PLAYERS,
     MATCHES
WHERE PLAYERS.PLAYERNO = MATCHES.PLAYERNO
  AND WON > LOST;

/*Query 05*/
SELECT PLAYERS.PLAYERNO, PLAYERS.NAME, SUM(AMOUNT)
FROM PLAYERS,
     PENALTIES
WHERE PLAYERS.PLAYERNO = PENALTIES.PLAYERNO
GROUP BY PLAYERS.PLAYERNO, PLAYERS.NAME
ORDER BY SUM(AMOUNT) ASC;

