/*Query 06*/
SELECT LOC
FROM EMP,
     DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
  AND ENAME = 'ALLEN';

/*Query 07*/
SELECT *
FROM EMP EMPLOYEE   --self-join
WHERE SAL >
      (SELECT SAL
       FROM EMP
       WHERE EMPNO = EMPLOYEE.MGR);

/*Query 08*/
SELECT COUNT(*), EXTRACT(YEAR FROM TO_DATE(HIREDATE, 'DD-MM-YYYY'))
FROM EMP
GROUP BY EXTRACT(YEAR FROM TO_DATE(HIREDATE, 'DD-MM-YYYY'))
ORDER BY EXTRACT(YEAR FROM TO_DATE(HIREDATE, 'DD-MM-YYYY'));

/*Query 09*/
SELECT *
FROM EMP
WHERE JOB IN
      (SELECT JOB
       FROM EMP
       WHERE DEPTNO =
             (SELECT DEPTNO
              FROM DEPT
              WHERE LOC = 'CHICAGO'));