/*Queries 02*/
SELECT LEVEL, LPAD(SUPER, 2 * LEVEL, '--') AS SUPER, SUB
FROM PARTS
CONNECT BY PRIOR SUB = SUPER
START WITH SUPER IN ('P3', 'P9');

/*Queries 03*/
SELECT *
FROM (SELECT LEVEL, LPAD(SUPER, 2 * LEVEL, '--') AS SUPER, SUB
      FROM PARTS
      CONNECT BY PRIOR SUB = SUPER
      START WITH SUPER = ('P1'))
WHERE SUB = 'P12';

/*Queries 04*/
SELECT *
FROM (SELECT LEVEL, LPAD(SUPER, 2 * LEVEL, '--') AS SUPER, SUB, price
      FROM PARTS
      CONNECT BY PRIOR SUB = SUPER
      START WITH SUPER = ('P1'))
WHERE PRICE > 20;