/*Queries 05*/
Select LEVEL, ENAME, LPAD(MGR, 2 * LEVEL, '--') AS MGR, EMPNO
FROM EMP
CONNECT BY PRIOR EMPNO = MGR
START WITH MGR =
           (SELECT EMPNO
            FROM EMP
            WHERE ENAME = 'JONES');

/*Queries 06*/
Select LEVEL, ENAME, LPAD(MGR, 10 - LEVEL * 2, '--') AS MGR, EMPNO
FROM EMP
CONNECT BY PRIOR MGR = EMPNO
START WITH EMPNO =
           (SELECT EMPNO
            FROM EMP
            WHERE ENAME = 'SMITH');

/*Queries 07*/
Select LEVEL, ROUND(AVG(SAL), 2)
FROM EMP
CONNECT BY PRIOR EMPNO = MGR
START WITH EMPNO =
           (SELECT EMPNO
            FROM EMP
            WHERE ENAME = 'KING')
GROUP BY LEVEL
ORDER BY LEVEL;