/*Query 01*/
SELECT COUNT(*), YEAR_JOINED
FROM PLAYERS
GROUP BY YEAR_JOINED;

/*Query 02*/
SELECT PLAYERNO, COUNT(*), AVG(AMOUNT)
FROM PENALTIES
GROUP BY PLAYERNO;

/*Query 03*/
SELECT EXTRACT(YEAR FROM TO_DATE(PEN_DATE, 'DD-MM-YYYY')), COUNT(*)
FROM PENALTIES
WHERE EXTRACT(YEAR FROM TO_DATE(PEN_DATE, 'DD-MM-YYYY')) < 1983
GROUP BY EXTRACT(YEAR FROM TO_DATE(PEN_DATE, 'DD-MM-YYYY'));

/*Query 04*/
SELECT TOWN, COUNT(*)
FROM PLAYERS
GROUP BY TOWN
HAVING COUNT(*) > 4;

/*Query 05*/
SELECT PLAYERNO, SUM(AMOUNT)
FROM PENALTIES
GROUP BY PLAYERNO
HAVING SUM(AMOUNT) > 150;

/*Query 06*/
SELECT NAME, INITIALS, PENALTIES.PLAYERNO
FROM PENALTIES,
     PLAYERS
WHERE PLAYERS.PLAYERNO = PENALTIES.PLAYERNO
GROUP BY NAME, INITIALS, PENALTIES.PLAYERNO
HAVING COUNT(PENALTIES.PLAYERNO) > 1;

/*Query 07*/
SELECT EXTRACT(YEAR FROM TO_DATE(PEN_DATE, 'DD-MM-YYYY'))
FROM PENALTIES
GROUP BY EXTRACT(YEAR FROM TO_DATE(PEN_DATE, 'DD-MM-YYYY'))
HAVING COUNT(*) = 2;

/*Query 08*/
SELECT NAME, INITIALS, PENALTIES.PLAYERNO
FROM PENALTIES,
     PLAYERS
WHERE AMOUNT > 40
  AND PLAYERS.PLAYERNO = PENALTIES.PLAYERNO
GROUP BY NAME, INITIALS, PENALTIES.PLAYERNO
HAVING COUNT(*) > 1;

/*Query 09*/
SELECT NAME, INITIALS
FROM PENALTIES,
     PLAYERS
WHERE PLAYERS.PLAYERNO = PENALTIES.PLAYERNO
GROUP BY NAME, INITIALS
HAVING SUM(PENALTIES.AMOUNT) >= ALL
       (SELECT SUM(AMOUNT)
        FROM PENALTIES
        GROUP BY PLAYERNO);

/*Query 10*/
SELECT EXTRACT(YEAR FROM TO_DATE(PEN_DATE, 'DD-MM-YYYY')), COUNT(*)
FROM PENALTIES
GROUP BY PEN_DATE
HAVING COUNT(*) >= ALL
       (SELECT COUNT(*)
        FROM PENALTIES
        GROUP BY PEN_DATE);

/*Query 11*/
SELECT PLAYERNO, TEAMNO, WON, LOST
FROM MATCHES
ORDER BY LOST DESC;
