/*Queries 01*/
INSERT INTO PLAYERS
VALUES (25, 'Leutgeb', 'EL', '1996', 'M', '2021', 'Birkenstraße', '6', '4600', 'Wels', '660-123456', '7777');
COMMIT;

/*Queries 02*/
UPDATE PLAYERS
SET SEX = 'W'
WHERE SEX = 'F';
COMMIT;

/*Queries 03*/
UPDATE PENALTIES
SET AMOUNT = (AMOUNT * 1.2);
COMMIT;

/*Queries 04*/
UPDATE PLAYERS
SET STREET   = (SELECT STREET FROM PLAYERS WHERE PLAYERNO = 6),
    HOUSENO  = (SELECT HOUSENO FROM PLAYERS WHERE PLAYERNO = 6),
    POSTCODE = (SELECT POSTCODE FROM PLAYERS WHERE PLAYERNO = 6),
    TOWN     = (SELECT TOWN FROM PLAYERS WHERE PLAYERNO = 6)
WHERE PLAYERNO = 95;
COMMIT;

/*Queries 05*/
DELETE PENALTIES
WHERE PLAYERNO = 44 AND (EXTRACT(YEAR FROM PEN_DATE) = 1980);
COMMIT;

/*Queries 06*/
COMMIT;

/*Queries 07*/
DELETE PENALTIES
    WHERE PLAYERNO =
          (SELECT PLAYERNO
          FROM TEAMS
          WHERE TEAMNO = 2);
SELECT *
    FROM PENALTIES;

/*Queries 08*/
SELECT *
    FROM PENALTIES;
ROLLBACK;

