/*Queries 09*/
UPDATE EMP E1
SET SAL = 0.8 * (SELECT AVG(SAL)
           FROM EMP E2
           WHERE E1.DEPTNO = E2.DEPTNO)
WHERE SAL < 0.8 * (SELECT AVG(SAL)
             FROM EMP E2
             WHERE E1.DEPTNO = E2.DEPTNO);
COMMIT;

/*Queries 10*/
INSERT
INTO EMP
VALUES (5325, 'LEUTGEB', 'PRESIDENT', NULL, '25-09-2021', 6000, NULL, 10);
COMMIT;

DELETE EMP
WHERE EMPNO =
      (SELECT EMPNO
       FROM EMP
       WHERE EXTRACT(YEAR FROM (HIREDATE)) >
             ((EXTRACT(YEAR FROM (SYSDATE)) - 35))); --change > to < to get the right value
COMMIT;

/*Queries 11*/
CREATE SEQUENCE NUM
    MINVALUE 50
    START WITH 50
    INCREMENT BY 10;

DROP SEQUENCE NUM;
/*Queries 12*/
INSERT INTO DEPT
(DEPT.DEPTNO, DEPT.DNAME,DEPT.LOC)
VALUES
(NUM.NEXTVAL, 'HTL', 'LEONDING');

SELECT *
FROM DEPT;

COMMIT;